version: "3.7"
services:
  tinyproxy-vpn:
    build: .
    image: tinyproxy-vpn
    container_name: tinyproxy-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    init: true
    ports:
      - 8888:8888/tcp
      - 8080:8080/tcp
    # command:
    environment:
      - USER=
      - PASSWORD=
      - FILE=netflix-stream.ovpn
      - NONROOT=no
      - DOT=on
      - BLOCK_MALICIOUS=on
      - BLOCK_NSA=off
      - UNBLOCK=
      - FIREWALL=on
      - EXTRA_SUBNETS=
      - TINYPROXY=on
      - TINYPROXY_LOG=Critical
      - TINYPROXY_USER=
      - TINYPROXY_PASSWORD=
      - SHADOWSOCKS=off
    volumes:
      - /home/georg/projects/openvpn-tinyproxy-docker/openvpn-config:/openvpn/configs
